participants:
  - email: person01@example.com
    name: Person 01
    active: true
  - email: person02@example.com
    name: Person 02
    active: true
  - email: person03@example.com
    name: Person 03
    active: true
  - email: person04@example.com
    name: Person 04
    active: true
  - email: person05@example.com
    name: Person 05
    active: true
  - email: person06@example.com
    name: Person 06
    active: true
  - email: person07@example.com
    name: Person 07
    active: true
  - email: person08@example.com
    name: Person 08
    active: true
  - email: person09@example.com
    name: Person 09
    active: true
  - email: person10@example.com
    name: Person 10
    active: true
  - email: person11@example.com
    name: Person 11
    active: true
  - email: person12@example.com
    name: Person 12
    active: true
  - email: person13@example.com
    name: Person 13
    active: true
  - email: person14@example.com
    name: Person 14
    active: true
  - email: person15@example.com
    name: Person 15
    active: true
  - email: person16@example.com
    name: Person 16
    active: true
  - email: person17@example.com
    name: Person 17
    active: true
  - email: person18@example.com
    name: Person 18
    active: true
  - email: person19@example.com
    name: Person 19
    active: true
  - email: person20@example.com
    name: Person 20
    active: true
  - email: person21@example.com
    name: Person 21
    active: true
  - email: person22@example.com
    name: Person 22
    active: true
  - email: person23@example.com
    name: Person 23
    active: true
  - email: person24@example.com
    name: Person 24
    active: true
  - email: person25@example.com
    name: Person 25
    active: true
  - email: person26@example.com
    name: Person 26
    active: true
  - email: person27@example.com
    name: Person 27
    active: true
  - email: person28@example.com
    name: Person 28
    active: true
  - email: person29@example.com
    name: Person 29
    active: true
  - email: person30@example.com
    name: Person 30
    active: true
  - email: person31@example.com
    name: Person 31
    active: true
  - email: person32@example.com
    name: Person 32
    active: true
  - email: person33@example.com
    name: Person 33
    active: true
  - email: person34@example.com
    name: Person 34
    active: true
  - email: person35@example.com
    name: Person 35
    active: true
  - email: person36@example.com
    name: Person 36
    active: true
  - email: person37@example.com
    name: Person 37
    active: true
  - email: person38@example.com
    name: Person 38
    active: true
  - email: person39@example.com
    name: Person 39
    active: true
  - email: person40@example.com
    name: Person 40
    active: true
  - email: person41@example.com
    name: Person 41
    active: true
  - email: person42@example.com
    name: Person 42
    active: true
  - email: person43@example.com
    name: Person 43
    active: true
  - email: person44@example.com
    name: Person 44
    active: true
  - email: person45@example.com
    name: Person 45
    active: true
  - email: person46@example.com
    name: Person 46
    active: true
  - email: person47@example.com
    name: Person 47
    active: true
  - email: person48@example.com
    name: Person 48
    active: true
  - email: person49@example.com
    name: Person 49
    active: true
  - email: person50@example.com
    name: Person 50
    active: true
